# Generated by Django 4.2 on 2023-09-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("permalink", models.URLField()),
                ("type", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("short_description", models.TextField()),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "regular_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_sales", models.IntegerField()),
                ("stock_quantity", models.IntegerField(blank=True, null=True)),
                ("stock_status", models.CharField(max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "shipping_class",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("parent_id", models.IntegerField(blank=True, null=True)),
                ("categories", models.TextField()),
                ("images", models.URLField()),
                ("attributes", models.TextField()),
                ("default_attributes", models.TextField()),
                ("variations", models.TextField()),
            ],
        ),
    ]
