# Generated by Django 4.2 on 2023-09-14 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productcategory_remove_product_attributes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="attributes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
