# Generated by Django 4.2 on 2023-09-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0007_remove_product_attributes_remove_product_categories_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
