# Generated by Django 4.2 on 2023-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_class",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_status",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="productmetadata",
            name="key",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="usercolumnpreference",
            name="column_name",
            field=models.CharField(max_length=250),
        ),
    ]
