# Generated by Django 4.2 on 2023-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_name_alter_product_shipping_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.TextField(),
        ),
    ]
