# Generated by Django 4.2 on 2023-09-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_class",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_status",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productmetadata",
            name="key",
            field=models.TextField(),
        ),
    ]
