# Generated by Django 4.2 on 2023-09-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_name_alter_product_shipping_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="product",
            name="permalink",
            field=models.URLField(max_length=1000),
        ),
    ]
