# Generated by Django 4.2 on 2023-09-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_product_images_alter_product_permalink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="default_attributes",
        ),
    ]
