# Generated by Django 4.2 on 2023-09-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0018_remove_productattribute_product_product_attributes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("private", "Private"),
                    ("publish", "Published"),
                    ("trash", "Trashed"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("instock", "In Stock"),
                    ("outofstock", "Out of Stock"),
                    ("onbackorder", "On Backorder"),
                ],
                default="instock",
                max_length=50,
            ),
        ),
    ]
